---
title: "PSA plots per gear"
author: "Leslie Roberson"
date: "08/02/2022"
output: html_document
---

## SI Figure 1 PSA plot

Final formatting was done in Adobe Illustrator

```{r setup, include=FALSE}

library(tidyverse)
library(here)
library(pillar)
library(forcats)
library(RColorBrewer)
library(ggrepel)
library(cowplot)
library(grid)
library(gridExtra)
library(ggpubr)

knitr::opts_chunk$set(echo = TRUE)
```

## SI Fig 1 (comparing to 123 score results)

colors for tax group then colors for range size
No species names labels

```{r prep plot dat}

## load vulnerability summary 
psaplot.dat <- read_csv(here("_results/Vulnerability/V_scores.csv")) ## first need to make the V123 scores
glimpse(psaplot.dat)

##prep
psaplot.dat <- psaplot.dat %>% mutate(tax_group=as_factor(class))
levels(psaplot.dat$tax_group)
psaplot.dat$tax_group <- fct_recode(psaplot.dat$tax_group, "Elasmobranchs"="Elasmobranchii", "Cetaceans"="Mammalia", "Sea turtles"="Reptilia")
levels(psaplot.dat$tax_group)
#      "Cetaceans"     "Sea turtles"   "Elasmobranchs" 
pal_taxgrp <- c("navy", "springgreen2", "slategray4")

## make data quality score numeric factor and rename gears for plot labels
psaplot.dat <- psaplot.dat %>% 
  mutate(data_qual123 = case_when(
           data_quality_score=="poor"~1, data_quality_score=="decent"~2, data_quality_score=="good"~3, TRUE~as.numeric(NA)),
         gear=case_when(
           gear=="GND"~"Drift gill nets", gear=="LLT"~"Longlines", gear=="PST"~"Purse seines", TRUE~""),
         gear=as_factor(gear))

```

## plot

```{r SI 6facets}

##<><>< prep data

SI.tax <- si.psa %>%
  ggplot() + 
  geom_point(aes(x=S, y=productivity, size=data_score_num, color=tax_group, alpha=data_score_num)) +
  scale_y_continuous(limits=c(1,3.1), breaks=seq(1,3,1), expand=expand_scale(add=c(0.2, 0.2))) +
  scale_x_continuous(limits=c(1,3.1), breaks=seq(1,3,1), expand=expand_scale(add=c(0.1, 0.1))) +
  scale_size_continuous(limits=c(1,3), breaks=seq(1,3,0.5), range=c(2.5, 0.5)) +
  scale_color_manual(values=pal_taxgrp) + 
  scale_alpha_continuous(range = c(0.3, 1)) +
  facet_wrap(~gear, nrow=1, strip.position="top") + # can put it right or left too
  labs(y="(   High)   Productivity   (Low    )", x= "(    Low)   Susceptibility   (High    )", color="", size="Data\nquality\nscore") +
  coord_flip() + 
  theme_bw() +
  theme(legend.position="none",
        strip.background =element_rect(fill="white"), # background of facet labels
        #strip.text.x = element_blank(), # remove facet labels
        panel.grid = element_blank()) +
  guides(size="none",
         alpha="none")
SI.tax

SI.risk <- si.psa %>%
  ggplot() + 
  geom_point(aes(x=S, y=productivity, size=data_score_num, color=ncells_spp, alpha=data_score_num)) +
  scale_y_continuous(limits=c(1,3.1), breaks=seq(1,3,1), expand=expand_scale(add=c(0.2, 0.2))) +
  scale_x_continuous(limits=c(1,3.1), breaks=seq(1,3,1), expand=expand_scale(add=c(0.1, 0.1))) +
  scale_size_continuous(limits=c(1,3), breaks=seq(1,3,0.5), range=c(2.5, 0.5)) +
  scale_color_viridis_c(option="magma", direction=-1) + 
  scale_alpha_continuous(range = c(0.7, 1)) +
  facet_wrap(~gear, nrow=1, strip.position="top") + # can put it right or left too
  labs(y="(   High)   Productivity   (Low    )", x= "(    Low)   Susceptibility   (High    )", color="", size="Data\nquality\nscore") +
  coord_flip() + 
  theme_bw() +
  theme(legend.position="none",
        strip.background =element_rect(fill="white"), # background of facet labels
        #strip.text.x = element_blank(), # remove facet labels
        panel.grid = element_blank()) +
  guides(size="none",
         alpha="none")
SI.risk
    
  
##<>><< make legends

legend_tax <- get_legend(
  SI.tax + 
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "right",
          legend.margin=margin(t=-0.5, r=0, b=0, l=0, unit="cm"))
)
legend_tax

legend_risk <- get_legend(
  SI.risk + 
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "right",
          legend.margin=margin(t=-0.5, r=0, b=0, l=0, unit="cm"))
)
legend_risk

#ggarrange(legend_gears, p.density + guides(fill="none"), p.bar + rremove("y.text") + guides(fill="none"),
#         labels=c("A", "B"),
#         nrow=2)

SI.grid <- grid.arrange(legend_tax,
             SI.tax + theme(legend.position="none",
                           legend.title=element_blank(),
                           axis.title.y=element_blank(),
                           axis.title.x=element_blank(),
                           axis.text.x=element_blank(),
                           axis.ticks.x=element_blank()),
             legend_risk,
             SI.risk + theme(legend.position="none",
                            legend.title=element_blank(),
                            axis.title.y=element_blank(),
                            axis.title.x=element_blank(),
                            strip.text.x=element_blank()),
            ncol=1, nrow=4,
            heights = c(0.3, 3, 0.3, 3))
SI.grid

ggsave(SI.grid, 
       width=7, height=6, units="in",
       dpi=600,
       filename="_results/figures/fig_psaplot/18april_SI_Vpsas_rev2.eps",
       device=cairo_ps)

```


